export const COURSE_LIST = [
  'AI (Generative & Agentic)',
  'Android App Development',
  'Artificial Intelligence',
  'AutoCAD',
  'AWS',
  'Business Analysis',
  'Car Design',
  'Clinical Trial & Research',
  'Cloud Computing',
  'Cyber Security & Ethical Hacking',
  'Data Analysis',
  'Data Science',
  'DevOps',
  'Digital Marketing',
  'DSA with Python',
  'Embedded System',
  'Finance',
  'Front End Web Development',
  'Full Stack Web Development',
  'Graphic Designing',
  'Human Resources & Management',
  'Hybrid Electric Vehicle',
  'Internet of Things',
  'Machine Learning',
  'Medical Coding',
  'Nanotechnology',
  'Operation & Supply Chain Management',
  'Product & Project Management',
  'Programming in Java',
  'Programming in Python',
  'Psychology',
  'Robotics',
  'Startup & Entrepreneurship',
  'Stock Marketing',
  'UI/UX',
  'VLSI'
];
